### ISSUE TITLE
Service provider >> Upload documents

### ISSUE THREAD

**Issue by rgnarok** [Gaurupasana/Carwazi-Issue-tracker#115]
Mention here what type of documents are required as how a user will know what he needs to upload

**Comment by atul-gautam-au6** [comment]
@rgnarok  i don't have any information about type of document

**Comment by rgnarok** [comment]
@atul-gautam-au6 add a text(only jpg , pdf etc required) Mention the type you are allowing

**Comment by atul-gautam-au6** [comment]
enable for .pdf
