### ISSUE TITLE
Change message while sharing the Invite code

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Gaurupasana/Carwazi-Issue-tracker#29]
@Gaurupasana pls provide the new message

**Comment by vishakhagurjarvayuz** [comment]
which invite code @technicalbirdVayuz

**Comment by Gaurupasana** [comment]
I’m inviting you to use Carwazi, a simple way to book car services. Here’s my code (4s7Al)- just enter it before you signup and you'll get 5 coins for booking your service.Hurry up !!.  https://g.....

@vishakhagurjarvayuz  @atul-gautam-au6  use this content

**Comment by Gaurupasana** [comment]
fixed
