### ISSUE TITLE
Deals and discount >>We are not able to select services on the basis of service provider. Because of this issue we are not able to create coupon code.

### ISSUE THREAD

**Issue by Gaurupasana** [Gaurupasana/Carwazi-Issue-tracker#62]

**Comment by atul-gautam-au6** [comment]
i was checked its working

**Comment by rgnarok** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/172066538-c3f0af13-1982-46a6-b82b-7f637e828a2f.png">
Not working @atul-gautam-au6
