### ISSUE TITLE
Working times section in edit Profile should have validation in place

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Gaurupasana/Carwazi-Issue-tracker#78]
@Gaurupasana PLease share the validations

**Comment by vayuzpriya** [comment]
![Screenshot_20211111-154357_CarwaziStore](https://user-images.githubusercontent.com/81085431/141280686-beb614e6-df4f-418f-b5ea-9283419390dd.jpg)
Screen left right space is not same.
Ui is not align as per design why

**Comment by Gaurupasana** [comment]
1. If we have selected the start time 9 am end time shouldn't be previous to 9 am, don't show previous time slots.
2. We have to change the time format at admin side too @atul-gautam-au6
