### ISSUE TITLE
Cannot update service provider profile from admin

### ISSUE THREAD

**Issue by rgnarok** [Gaurupasana/Carwazi-Issue-tracker#86]
- Cannot update service provider profile from admin

**Comment by atul-gautam-au6** [comment]
@rgnarok please share problematic  screen shot here

**Comment by rgnarok** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/172067066-70702a4a-74a1-429c-8823-69b7c600f8df.png">
not able to update here the details which i am adding @atul-gautam-au6
